import { StyleSheet } from 'react-native';
import { createThemedStyles } from '../../theme/createThemedStyles';
import { fontFamily, header as headerTokens } from '../../theme/tokens';

export const createAppHeaderStyles = createThemedStyles(
  (theme, isRTL?: boolean) => ({
    root: {
      backgroundColor: theme.backgroundSecondary,
      zIndex: 10,
      shadowColor: theme.textPrimary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
    presetHome: {
      paddingTop: 20,
      paddingBottom: 10,
      backgroundColor: theme.surface,
    },
    presetBack: {
      paddingTop: 20,
      paddingBottom: 10,
      backgroundColor: theme.surface,
    },
    navbarHome: {
      paddingHorizontal: 20,
      height: 'auto',
    },
    navbarBack: {
      paddingHorizontal: 20,
      height: 'auto',
    },
    transparent: {
      backgroundColor: 'transparent',
      borderBottomWidth: 0,
      shadowOpacity: 0,
      elevation: 0,
    },
    navbar: {
      height: 60,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
    },
    headerContainer: {
      height: 64,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 8,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    iconButton: {
      width: 40,
      height: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    titleContainer: {
      flex: 1,
      marginStart: 8,
    },
    titleText: {
      color: theme.textPrimary,
      textAlign: 'left',
    },
    subtitleText: {
      color: theme.textSecondary,
      fontSize: 9,
      letterSpacing: 1,
      fontWeight: '600',
      textAlign: 'left',
    },
    actions: {
      flexDirection: 'row',
    },
    searchField: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.surfaceSecondary,
      height: 40,
      borderRadius: 8,
      paddingHorizontal: 12,
      marginHorizontal: 8,
    },
    searchInput: {
      flex: 1,
      color: theme.textPrimary,
      fontSize: 16,
    },
    gradientHeader: {
      width: '100%',
      borderBottomLeftRadius: headerTokens.borderRadius,
      borderBottomRightRadius: headerTokens.borderRadius,
      overflow: 'hidden',
    },
    gradientHeaderContent: {
      paddingHorizontal: headerTokens.contentPaddingHorizontal,
      paddingBottom: headerTokens.contentPaddingBottom,
    },
    gsHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: headerTokens.rowMarginBottom,
      minHeight: headerTokens.rowMinHeight,
    },
    gsBackBtnPill: {
      width: headerTokens.iconButtonSize,
      height: headerTokens.iconButtonSize,
      borderRadius: headerTokens.iconButtonRadius,
      backgroundColor: theme.headerActionBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    gsHeaderLeftSlot: {
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: headerTokens.iconButtonSize,
      minHeight: headerTokens.iconButtonSize,
    },
    headerBadge: {
      position: 'absolute',
      top: -4,
      right: -4,
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
    },
    gsTitleWrapper: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      marginHorizontal: 16,
    },
    gsHeaderTitle: {
      color: theme.headerText,
      textAlign: 'center',
    },
    gsActionBtn: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    gsSearchShell: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.surfacePrimary,
      height: 44,
      borderRadius: 10,
      paddingHorizontal: 16,
      borderWidth: 0,
      shadowColor: theme.shadowColorAlt,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: theme.shadowOpacityHeader,
      shadowRadius: 12,
      elevation: 4,
    },
    gsSearchInput: {
      flex: 1,
      fontSize: 15,
      color: theme.textPrimary,
      paddingTop: 0,
      paddingBottom: 0,
      marginHorizontal: 8,
      height: '100%',
    },
    gsScanBtn: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: theme.surfaceBrand,
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: 4,
    },
    gsClearBtn: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: 4,
    },
    gsFilterBtn: {
      marginLeft: 16,
      width: 46,
      height: 46,
      backgroundColor: theme.surfaceBrandMuted,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    gsRecentSearchesContainer: {
      marginTop: 12,
    },
    gsRecentHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    gsSectionLabel: {
      fontSize: 11,
      fontWeight: '600',
      letterSpacing: 1,
      color: theme.headerText,
      opacity: 0.9,
    },
    gsRecentLine: {
      flex: 1,
      height: 1,
      backgroundColor: theme.borderOnBrand,
      marginLeft: 12,
    },
    gsChipsScroll: {
      flexGrow: 0,
      marginHorizontal: -20,
    },
    gsChipsScrollContent: {
      paddingHorizontal: 20,
      gap: 10,
    },
    gsChip: {
      backgroundColor: theme.surfacePrimary,
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 16,
    },
    gsChipText: {
      fontSize: 13,
      fontWeight: '500',
      color: theme.textSecondary,
    },
    orgSwitcher: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      marginStart: 8,
    },
    profileButton: {
      marginStart: 8,
      justifyContent: 'center',
    },
    greeting: {
      color: theme.headerText,
    },
    subGreeting: {
      marginTop: 2,
      color: theme.headerTextMuted,
    },
    headerIcons: {
      flexDirection: 'row',
    },
    dashboardIconButton: {
      backgroundColor: theme.headerActionBg,
      width: headerTokens.iconButtonSize - 4,
      height: headerTokens.iconButtonSize - 4,
      borderRadius: headerTokens.iconButtonRadius,
      marginStart: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    badge: {
      position: 'absolute',
      top: 8,
      right: 8,
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.error,
      borderWidth: 1,
      borderColor: theme.border,
    },
    commonTitleContainer: {
      position: 'absolute',
      left: 56,
      right: 56,
      top: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'center',
    },
    commonTitleText: {
      color: theme.textPrimary,
      textAlign: 'center',
    },
    scannerStatusContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.surfaceSecondary,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 16,
      marginStart: 8,
    },
    scannerStatusDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      marginEnd: 6,
    },
    scannerStatusText: {
      color: theme.textSecondary,
      fontSize: 10,
      fontWeight: 'bold',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    scannerZebraPill: {
      backgroundColor: theme.surface,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 8,
      marginStart: 8,
      borderWidth: 1,
      borderColor: theme.divider,
    },
    scannerZebraText: {
      color: theme.primary,
      fontSize: 9,
      fontWeight: '900',
      letterSpacing: 1,
    },
    absolute: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      zIndex: 100,
    },
    slot: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    center: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      marginHorizontal: 8,
    },
    centerStart: {
      alignItems: 'flex-start',
      justifyContent: 'center',
    },
    title: {
      textAlign: 'center',
      color: theme.textPrimary,
      letterSpacing: -0.3,
    },
    subtitle: {
      fontSize: 11,
      color: theme.textSecondary,
      marginTop: 1,
      fontWeight: '500',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    actionButton: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: 'transparent',
    },
    headerPrimaryActionText: {
      color: theme.primary,
      fontFamily: fontFamily.semibold,
      fontSize: 14,
    },
    headerActionsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    headerTextAction: {
      color: theme.headerText,
      fontFamily: fontFamily.semibold,
      fontSize: 15,
      paddingHorizontal: 4,
      paddingVertical: 6,
    },
    headerSaveAction: {
      backgroundColor: theme.surfacePrimary,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 10,
      minWidth: 64,
      alignItems: 'center',
    },
    headerSaveActionText: {
      color: theme.primary,
      fontFamily: fontFamily.semibold,
      fontSize: 14,
    },
    headerSaveActionDisabled: {
      opacity: 0.5,
    },
    actionButtonPressed: {
      backgroundColor: theme.surfaceSecondary,
      borderColor: theme.divider,
    },
  }),
);
